### PR TITLE
Lint gofmt

### PR DESCRIPTION
**Pull request by LaPingvino**
Adding gofmt so #229 can be closed

### CODE REVIEW

**Comment by LaPingvino** [comment]
@afinkenstadt it seems you need to confirm that you are okay with this :smiley:

**Comment by afinkenstadt** [comment]
I'm okay with it.  I hardly consider the work "creative expression" enough to worry. :)

--Andrew William Finkenstadt

**Comment by afinkenstadt** [comment]
:+1:

**Comment by adg** [comment]
Can you please just squash all this into the one commit, authored by @LaPingvino ?

**Comment by LaPingvino** [comment]
Done :)

**Comment by LaPingvino** [comment]
The change in graph.go breaks the build (i not known outside the if), rolling back the change only in that file.

**Comment by LaPingvino** [comment]
Change has been applied, pr doesn't break the build any more

**Comment by garyburd** [comment]
Not LGTM

The templates must be updated to match this change.

**Comment by LaPingvino** [comment]
Great catch, should be fixed now.

**Comment by LaPingvino** [comment]
@garyburd just because after the correction this PR remained further untouched, what do you think of it now?

**Comment by garyburd** [comment]
LGTM

**Pull request merged**
