### PR TITLE
golint fixes

### PR DESCRIPTION
**Pull request by afinkenstadt**

### CODE REVIEW

**Comment by garyburd** [comment]
The file graph.go does not compile. This is the second or third time that somebody has submitted a PR with this error. The code should be restructured to avoid the bad recommendation from golint.

**Comment by afinkenstadt** [comment]
Yeah, that's my bad for not setting up a real compilation environment.  The problem is the locality of reference of `i` stays within the `if` check.

**Comment by garyburd** [comment]
Not only should you compile the code, you should carefully check each change for correctness.

**Comment by garyburd** [comment]
Squash the changes.

**Comment by afinkenstadt** [comment]
Will close and re-open a new PR.

**Pull request closed without merging**
