### PR TITLE
Updating snappy import path

### PR DESCRIPTION
**Pull request by stephens2424**

### CODE REVIEW

**Comment by stephens2424** [comment]
I signed it!

**Comment by shurcooL** [comment]
Hi. I was going to make a PR to fix this issue, but I could not do it because the new canonical import path of `snappy` package is unclear. Its documentation points to one string, but in reality it seems to be another.

See https://github.com/golang/snappy/issues/12.

That issue has been open for 13 days and so far no response (/cc @nigeltao). I don't think this PR should be merged until that issue is resolved and the canonical import path is stated. The README still says `github.com/google/go-snappy/snappy` which isn't matching your change.

**Comment by adg** [comment]
@nigeltao - what's the right move here?

**Comment by shurcooL** [comment]
golang/snappy#12 has been resolved in https://github.com/golang/snappy/commit/eaa750b9bf4dcb7cb20454be850613b66cda3273, and the correct canonical import path for `snappy` is now `github.com/golang/snappy/snappy`.

This PR incorrectly uses `github.com/golang/snappy` as the import path and that should be fixed before merging.

**Comment by stephens2424** [comment]
Fixed

**Comment by adg** [comment]
Can you please squash your pair of commits into just the one?

**Comment by shurcooL** [comment]
LGTM. I would imagine the maintainers would prefer if you squashed it into one commit.

**Comment by stephens2424** [comment]
rebase :)

**Comment by adg** [comment]
Thanks

**Pull request merged**
