### PR TITLE
Correct typo visible in documentation

### PR DESCRIPTION
**Pull request by LaPingvino**

### CODE REVIEW

**Comment by LaPingvino** [comment]
Signed the CLA on personal title

**Comment by shurcooL** [comment]
LGTM (fwiw).

**Comment by garyburd** [comment]
LGTM

**Comment by slimsag** [comment]
If it's not troublesome for me to ask: is @googlebot going to be used to allow PR's to other Go repositories in the future (if it's not already)? I find it very nifty is all! =)

**Comment by adg** [comment]
On 9 February 2015 at 22:38, Stephen Gutekanst <notifications@github.com>
wrote:

> If it's not troublesome for me to ask: is @googlebot
> <https://github.com/googlebot> going to be used to allow PR's to other Go
> repositories in the future (if it's not already)? I find it very nifty is
> all! =)
>

No

**Pull request merged**
