### PR TITLE
Add jump to identifier on package pages.

### PR DESCRIPTION
**Pull request by garyburd**
The "f" keyboard shortcut opens a modal dialog with a list of all
exported identifiers on the page. Clicking an item closes the modal and
scrolls the page to the identifier. A text input filters the list.

Remove unused Javascript code.

A demo of of the feature is available at http://gary.burd.info/demo/.

### CODE REVIEW

**Comment by shurcooL** [comment]
If you're looking for it, I'd like to provide feedback regarding the usability of this feature.

Disclosure in advance, I am a touch typist and I have a mouse to the right of my keyboard. I would imagine this is a common setup of the target audience, but certainly not all. But my feedback is based on those assumptions.

The feedback is also based on my limited experience of reading your PR description, and playing with the demo you've provided. I may have missed/overlooked or been unaware of certain features. If so, let me know, and I'll adjust my feedback, but it's also worth noting perhaps the discoverability is low.

Consider a situation where I get to the godoc of `net/http` and I want to look up the docs for `Get` method.

1. On your demo page, I press ".".
2. I type "g", "e", "t" and see the results narrow down to just 3:

   image

3. At this point, I'd like to select the second entry and navigate there. I see no way to do it with the keyboard. Pressing down and up arrow keys simply moves my cursor within the text box.

   It appears the only way to select the second entry is to click it with the mouse. This requires me to take my right hand off the keyboard towards the mouse, moving it over 2nd entry in the list and clicking.

I see three disadvantages in that interaction compared to what I'm used to and what I've used in other UIs, that serve to reduce my performance as a user:

- The "." key is on the right hand side of most keyboards. Typically when browsing godoc.org in a browser, I have my left hand on the left hand side of the keyboard, and right hand on the mouse. In that case, pressing "." requires me to move my right hand.
   - I think it would be better if this shortcut were on the left side of the keyboard, easily accessible using left hand. E.g., keys "s" or "g" (assuming qwerty or similar layout) would work better in this regard.

- Using this UI requires the use of mouse and cannot be done with keyboard only. It requires alternating input from keyboard and mouse, which means you have to move your hands.
   - For optimal top performance, I think the UI should be made usable with keyboard only (for all steps).

- There are relatively slow blocking animations when the overlay appears, when filtering results, and when the overlay disappears after a target identifier is clicked. These blocking animations slow down my performance and do not allow me to navigate to symbols as fast as I could if they weren't there.
    - The animations should either not be blocking, should be made faster, or removed altogether.

- If I accidentally click on the wrong entry, or if I'm not sure which of multiple entries I want to see, it's difficult and slow to open the overlay, type again what I had previously typed in the filter text box, and pick another entry.
   - It would be useful to be able to navigate between multiple filtered entries quickly, without having to close/reopen overlay.

I think if those suggestions can be addressed, this mode can be much better and more useful.

**Comment by LaPingvino** [comment]
I'm a dvorak typist, so assuming qwerty nerves me a little ;) but that's usually not too hard to overcome (even Vim, Wingo etc work great for me :wink:). But yes, I do agree with @shurcooL's feedback, and it seems a little slow to me...

**Comment by garyburd** [comment]
Please look at the demo again. 

Type "?" to see the full list of keyboard shortcuts supported by godoc.org.

**Comment by shurcooL** [comment]
The new version is much, much better and addresses most of the issues I've raised. I'll try to play with it more and provide more detailed feedback.

**Comment by LaPingvino** [comment]
Is it correct that I still have to click the item instead of arrow keys/enter to jump there?

**Comment by shurcooL** [comment]
No, arrow keys also work now. Try pressing down and up arrow keys.

It's a little strange that by default no entry is selected, and pressing down arrow selects the first one.

**Comment by garyburd** [comment]
I updated the logic so that there's always an item selected. Please look again.

**Comment by shurcooL** [comment]
That change is positive. I also like that it no longer loops around when at the very top or bottom.

I have some more suggestions, feel free to adopt them if you agree/think it's worth it.

1. I suggest matching the display format of the results with what godoc shows.

  For example, consider `http.Request`. Here's how it looks like on godoc:

 image

  This is what it looks like in the results:

   image

  Note that the word order is reversed.

  Another example,

  image

  In results, it is:

  image

  I can't be sure if this is universal, but for me, it's definitely true that I've trained myself to recognize the Go-like syntax patterns more easily. Seeing `Request type` instead of `type Request` is a little harder for me to recognize/find, and feels less optimal.

**Comment by shurcooL** [comment]
That said, I feel that at this point this new UI is quite good and useful. While I think there can be further improvements made to it (which is debatable, others may or may not agree with my suggestions) and I'd really like to see them happen, it's not a requirement for them to be done before this is merged.

So, I'll say the current version LGTM as is, but if you're looking for more feedback/suggestions for improvement, I definitely have more I can provide.

**Comment by garyburd** [comment]
I tried moving the identifier kind to the left. I think this makes the list more difficult to scan because the identifiers are not aligned.

@adg Please take a look.

**Comment by shurcooL** [comment]
> I tried moving the identifier kind to the left. I think this makes the list more difficult to scan because the identifiers are not aligned.

Have you tried using a monospaced font?

**Comment by LaPingvino** [comment]
Great, now it's usable :+1:

**Comment by adg** [comment]
LGTM

**Comment by adg** [comment]
This is now live.

**Pull request merged**
