### PR TITLE
Return all packages from database.Packages

### LINKED ISSUE #339: Mismatch in count, list and graph of imports when some of imports are (currently) invalid.
Due to packages moving, being renamed, or deleted, sometimes there are Go packages that import invalid or non-existent Go packages. Such code would not compile (unless you have vendored dependencies, etc.), but its documentation can and is still displayed by godoc.org.

However, when a Go package imports an invalid import path, there is an inconsistency between the number of imports, the list of imports, and the graph of imports.

Reproduce case:

https://godoc.org/gist.github.com/3ccb35092336d9362883.git

It imports a total of 3 Go packages. Two valid Go packages and one invalid one (it's a folder that contains no .go files). It would fail to compile. However, notice that:

image

Yet when you click that link, only 2 packages (the valid ones) are listed:

https://godoc.org/gist.github.com/3ccb35092336d9362883.git?imports

image

The graph view shows all imports:

https://godoc.org/gist.github.com/3ccb35092336d9362883.git?import-graph&hide=1

image

Since godoc.org doesn't check if Go packages compile, it shouldn't try to hide them. I am guessing it's an unintended bug.

Pretty minor issue, reporting because I noticed it.

**Edit:** Unfortunately, I deleted the original gist that was used to demonstrate the issue because I forgot what it was needed for. So I've re-created another one that reproduces the issue and updated links above. It works equally well.

### PR DESCRIPTION
**Pull request by lucidlime**
Fixes #339

### CODE REVIEW

**Comment by shurcooL** [comment]
Having briefly looked at the database code, this does look like it would fix the problem. However, have you ensured this doesn't have any other undesired side-effects? Is `Database.Packages` used anywhere else?

**Comment by lucidlime** [comment]
I examined all uses of the Packages method before changing any code. The fix is appropriate for all uses of the method.

**Comment by shurcooL** [comment]
I've looked more into the database code, and I agree, this should be a safe change to make.

Here's the meaning of `kind` values:

> kind: p=package, c=command, d=directory with no go files

So this change makes `database.Packages` return entries that are directories not containing .go files. Given how this resolves #339, I think it makes sense. Such directories evolve, and may have .go files at some time, then stop having .go files, then have .go files once again. If some other Go package imports a given import path, then it makes sense for it to be consistently counted and displayed as an import, even if it's not a valid import path (according to some way of measuring that).

In theory, this package is public and this would be a behavior change. But according to https://godoc.org/github.com/golang/gddo/database?importers, there's only a few users, and they're all either forks of `gddo` or modified experimental versions of `gddo`, so this change shouldn't affect them negatively.

**Comment by shurcooL** [comment]
I have only one comment, and then LGTM.

Can you add a commit message to the commit that describes the rationale for the change? Otherwise, someone looking at `git log` will see this change as black magic. The reference to an issue this resolves helps, but it's better to also describe in with a short phrase. For example, something like:

> Do not skip directories containing no .go files when calling Database.Packages. This allows a more consistent display of packages that are being imported.
> 
> Fixes #339.

Thanks for fixing this!

**Pull request merged**
